# packages/backend/Cargo.toml
[package]
name = "backend"
version = "1.0.0"
edition = "2021"

[dependencies]
axum = "0.8.6"
bytes = "1.10.1"
reqwest = { version = "0.12.24", features = ["socks", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
socketioxide = { version = "0.18.0" }
tokio = { version = "1.48.0", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
tower-http = { version = "0.6.6", features = ["cors"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.2", features = ["env-filter"] }
http = "1.3.0"
url = "2.5.7"
sha2 = "0.10.9"
hex = "0.4.3"
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
futures-util = "0.3.31"
dashmap = "6.1.0"
tokio-stream = "0.1.17"
once_cell = "1.21.3"
tokio-socks = "0.5.2"
tokio-native-tls = "0.3.1"
native-tls = "0.2.14"
thiserror = "2.0.17"
anyhow = "1.0.100"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio", "macros", "chrono"] }
chrono = { version = "0.4.42", features = ["serde"] }
tokio-retry = "0.3.0"
flate2 = "1.1.5"
axum-server = { version = "0.8", default-features = false, features = ["tls-rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2"
ts-rs = { version = "11.1.0", features = ["format"] }

[profile.dev]
incremental = true
split-debuginfo = "unpacked"

[[bin]]
name = "backend-core"
path = "src/bin/core.rs"

[[bin]]
name = "backend-market"
path = "src/bin/market.rs"
